Update chapter3.md
cisagov/LME pull request #29
Opened 2023-11-10 20:01 UTC by dkorzhevin

Changed winlogbeat 8.5.0 link to one, that allows user to download not only zip, but also sha512 control sum and also choose between zip and MSI.

#  #

## 🗣 Description ##

## 💭 Motivation and context ##

## 🧪 Testing ##

## ✅ Pre-approval checklist ##

- [ ] This PR has an informative and human-readable title.
- [ ] Changes are limited to a single goal - *eschew scope creep!*
- [ ] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [ ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [ ] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2023-11-13 22:12 UTC, dkorzhevin commented
Will also add simple guide, how to check SHA512 of downloaded agent

2023-11-17 01:30 UTC, mreeve-snl requested changes
I think this change is fine and makes sense, IIRC we'll be changing to 8.11.1 with the latest release to update versioning and such. 
Would you be able to change the URL to match our version? 
https://www.elastic.co/downloads/past-releases/winlogbeat-8-11-1

2023-11-17 20:12 UTC, dkorzhevin reviewed
Changed winlogbeat to version 8.11.1 @mreeve-snl

2023-11-20 18:42 UTC, mreeve-snl approved these changes
LGTM

2023-11-20 18:57 UTC, cbaxley approved these changes

2023-11-20 19:01 UTC, merged