Merge Release-1.1.0-small to Main
cisagov/LME pull request #63
Opened 2023-11-21 20:16 UTC by mreeve-snl

Removes breaking changes in the release so dashboards and other QOL improvements can be released, and further testing/refactoring can be done on other release-1.1.0 code

## 🗣 Description ##

Removes the following files from the release-1.1.0, and resets them back to release 1.0 state. 
```
╰─$ git status
On branch release-1.1.0-small
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   Chapter 2 Files/SCCM Deployment/Uninstall_Sysmon64.ps1
        modified:   Chapter 3 Files/dashboard_update.sh
        modified:   Chapter 3 Files/deploy.sh
        modified:   Chapter 3 Files/docker-compose-stack.yml
        modified:   Chapter 3 Files/lme_update.sh
        modified:   docs/markdown/chapter3/chapter3.md
        modified:   docs/markdown/maintenance/upgrading.md
```

## 💭 Motivation and context ##

During testing, the current deployment process and setup creates difficulties and bottlenecks that were unexpected, and need to be refactored, improved, and updated. 

## 🧪 Testing ##

the dashboards and new script have been tested.

2023-11-27 11:50 UTC, cbaxley requested changes

2023-11-27 11:50 UTC, cbaxley commented on docs/markdown/chapter4.md
> +Found under both "Analytics" -> "Dashboard," dashboards are a great way to visualize LME data. LME comes with several dashboards. Take some time to get familiar with the different dashboards already
Remove word "both"

2023-11-27 11:50 UTC, cbaxley commented on docs/markdown/reference/troubleshooting.md
> +Usually if you have issues with containers restarting there is probably something wrong with your host or the container itself. Lik in the above sample, a wrong password could be prevent the Elastic
Change Lik to Like

2023-11-28 17:55 UTC, ddiabe approved these changes

2023-11-28 20:55 UTC, mitchelbaker-cisa commented on Chapter 3 Files/deploy.sh
> +  usage
Nice, keeping things DRY / reusable

2023-11-28 21:18 UTC, mitchelbaker-cisa commented on docs/markdown/reference/troubleshooting.md
> +To fix this you can change the permissions to what the conatiner expects:
Container is misspelled

2023-11-28 21:37 UTC, mitchelbaker-cisa approved these changes

2023-11-28 22:06 UTC, rgbrow1949 approved these changes
Approved!

2023-11-28 22:07 UTC, cbaxley approved these changes

2023-11-28 22:08 UTC, merged